services:
  postgres:
    image: postgres:latest
    container_name: postgres_e-commerce
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: idpdb
    ports:
      - "54321:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: backend_e-commerce
    restart: always
    depends_on:
      - postgres
    ports:
      - "3002:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    container_name: frontend_e-commerce
    restart: always
    depends_on:
      - backend
    ports:
      - "8181:80"
    volumes:
      - ./frontend/app:/usr/share/nginx/html

volumes:
  postgres_data:
